### PR TITLE
Fixes #5

### LINKED ISSUE #5: is-not-registered.php
+ Lines 19-20 and 29-30, are equals, so, it must be out of the if statements.
+ The first and the second ifs are mutually exclusive, so, a else if must replace the second if.
+ The else at line 40 must be after the second if because, if email nor nick fields are sent, then the request sent a wrong data.
+ The if at line 33, is not necessary because the statement will never be wrong but the if and the else inside it are ok

### PR DESCRIPTION
**Pull request by S026**

### CODE REVIEW

File: php/is-not-registered.php [hunk 1]
```diff
@@ -13,32 +13,23 @@
...
-
 		$stmt = $db->prepare('SELECT COUNT(*) FROM user WHERE email = ?');
 		$stmt->bind_param('s', $email);
-		$stmt->execute();
-		$stmt->bind_result($result)
-
 	}
-
-	if (isset($_POST ['nick']))
+	else
```
Comment (betoecs) [inline php/is-not-registered.php]: You missed the if condition to determine if `$_POST ['nick']` is set

**Review by betoecs — CHANGES_REQUESTED** [review]
